export const 
FETCH_PRODUCTS = 'FETCH_PRODUCTS',
FETCHING_PRODUCTS = 'FETCHING_PRODUCTS',
FETCH_SUCCESS = 'FETCH_SUCCESS',
FETCH_ERROR = 'FETCH_ERROR',
ADD_PRODUCT_TO_BAG = 'ADD_PRODUCT_TO_BAG',
REMOVE_PRODUCT_FROM_BAG = 'REMOVE_PRODUCT_FROM_BAG'
;